### ISSUE TITLE
Web application could not be started

### ISSUE THREAD

**Issue by mawe-net** [ATIX-AG/foreman_scc_manager#42]
ERF73-0602 [Foreman::PermissionMissingException]: some permissions were not found: ["use_scc", "view_scc", "new_scc", "edit_scc", "delete_scc", "sync_scc", :view_scc, :use_scc, :new_scc, :edit_scc, :delete_scc, :sync_scc] (Foreman::PermissionMissingException)

Fresh install CentOS 7.8 - Katello 3.15 - tfm-rubygem-foreman_scc_manager-1.8.3-1.fm2_0.el7

Will there be a new version for Katello 3.15?

Great Job! Thanks  a lot!

**Comment by m-bucher** [comment]
This seems to be due to duplicate permissions within the database.
You can solve this manually by removing the duplicates in the postgresql-console:
```
# su postgres -c 'psql katello'

foreman=# SELECT * FROM permissions WHERE name='view_scc';
 id  |   name   | resource_type |         created_at         |         updated_at         
-----+----------+---------------+----------------------------+----------------------------
 240 | view_scc |               | 2020-06-12 07:35:56.199982 | 2020-06-12 07:35:56.199982
 241 | view_scc |               | 2020-06-12 07:35:56.210071 | 2020-06-12 07:35:56.210071
(2 rows)

foreman=# DELETE FROM permissions WHERE id=241;
...
foreman=# \q
# 
```
Do this for all the permissions mentioned in the error and make sure that the 'SELECT'-result only has one entry per permission.

We are not sure why this happens, so feel free to leave this issue open even if you fixed it manually.

**Comment by mawe-net** [comment]
Thanks a lot for your quick answer!
You were right. In my case there have been duplcate entries for 'view_scc' and 'use_scc'. After cleaning up it works well.

If you do a clean setup of katello with a minimal parameterset your DB Name will be foreman. So my DB was foreman (just as remark).

regards Martin
